// GENERATED by scripts/gen-model.mjs from pb/schema.json — do not edit.
//
// The database enforces these shapes; this file is how the UI knows them.
// Editing it by hand puts the two back out of step, which is the problem it
// exists to solve. Change pb/schema.json and regenerate.

export interface Users {
  id: string;
}

export interface Brands {
  id: string;
  name: string;
  timezone?: string;
  default_locale?: string;
  created: string;
  updated: string;
}

export const ASSETS_KIND = ['image', 'video', 'audio', 'document'] as const;
export type AssetsKind = typeof ASSETS_KIND[number];

export interface Assets {
  id: string;
  brand?: string;
  file?: string;
  kind?: "image" | "video" | "audio" | "document";
  alt_text?: string;
  checksum?: string;
  created: string;
  updated: string;
}

export const POSTS_STATUS = ['draft', 'in_review', 'approved', 'scheduled', 'published', 'failed'] as const;
export type PostsStatus = typeof POSTS_STATUS[number];

export interface Posts {
  id: string;
  brand?: string;
  title: string;
  body?: string;
  slot_at?: string;
  status?: "draft" | "in_review" | "approved" | "scheduled" | "published" | "failed";
  approved_by?: string;
  created: string;
  updated: string;
}

export const VARIANTS_NETWORK = ['youtube', 'facebook', 'instagram', 'tiktok', 'linkedin'] as const;
export type VariantsNetwork = typeof VARIANTS_NETWORK[number];

export const VARIANTS_STATE = ['draft', 'scheduled', 'queued', 'published', 'failed', 'handoff', 'skipped'] as const;
export type VariantsState = typeof VARIANTS_STATE[number];

export interface Variants {
  id: string;
  post?: string;
  network?: "youtube" | "facebook" | "instagram" | "tiktok" | "linkedin";
  body?: string;
  media?: string;
  first_comment?: string;
  state?: "draft" | "scheduled" | "queued" | "published" | "failed" | "handoff" | "skipped";
  gateway_job_id?: string;
  network_url?: string;
  telegram_message_id?: number;
  last_error?: string;
  created: string;
  updated: string;
}
